### DISCUSSION TITLE
CoreShop 4 - Extending Frontend Controllers

### DISCUSSION THREAD

**Discussion by Stefan-JustMe69-SQ** [coreshop/CoreShop#2637] [General]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I followed documentation
https://docs.coreshop.org/CoreShop/Development/Frontend_Bundle/
an created own class TemplateConfigurator

```php
<?php

declare(strict_types=1);

namespace FrontendBundle\CoreShop\TemplateConfigurator;

use CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface;

class TemplateConfigurator implements TemplateConfiguratorInterface
{
    public function findTemplate(string $templateName): string
    {
        return sprintf('coreshop/%s.twig', $templateName);
    }
}


    FrontendBundle\CoreShop\TemplateConfigurator\TemplateConfigurator:
        decorates: 'CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfigurator'
        public: true


```

I created controller IndexController and followed description in
https://docs.coreshop.org/CoreShop/Development/Frontend_Bundle/Controllers
and created controller and configuration as described

my class:
```php
<?php

declare(strict_types=1);

namespace FrontendBundle\CoreShop\Controller;

use CoreShop\Bundle\FrontendBundle\Controller\FrontendController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class IndexController extends FrontendController
{

    public function indexAction(Request $request): Response
    {
        return $this->render($this->getTemplateConfigurator()->findTemplate('Index/index.html'));
    }
}
```

my configs:
```
    FrontendBundle\CoreShop\Controller\IndexController:
        public: true
        arguments:
            - '@service_container'

core_shop_frontend:
    controllers:
        index: FrontendBundle\CoreShop\Controller\IndexController
```

I'm getting error:
```
The "CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

How to fix that?

**Comment by dpfaffenbauer** [comment]
You don't need to extend from the FrontendController and use parameter injection instead.

**Comment by Stefan-JustMe69-SQ** [comment]
Example somewhere?

**Reply by dpfaffenbauer** [reply]
no, unfortunately not. That is plain Symfony of how to inject things into the controller.

**Comment by Stefan-JustMe69-SQ** [comment]
same error with

```php
use CoreShop\Bundle\FrontendBundle\Controller\IndexController as BaseController;
use CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class IndexController extends BaseController
{
    public function __construct(protected TemplateConfiguratorInterface $templateConfigurator, protected $container)
    {
        parent::__construct($this->container);
    }


```

and
```
    FrontendBundle\CoreShop\Controller\IndexController:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - 'controller.service_arguments'
            - 'container.service_subscriber'
        arguments:
            - '@CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface'
            - '@service_container'
```

![grafik](https://github.com/coreshop/CoreShop/assets/23456403/79231a25-b7fb-4f3f-85e5-cc13bc16c532)

**Comment by dpfaffenbauer** [comment]
```php

use CoreShop\Bundle\FrontendBundle\Controller\IndexController as BaseController;
use CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class IndexController extends BaseController
{
    public function indexAction(Request $request, TemplateConfiguratorInterface $templateConfigurator): Response
    {
        return $this->render($templateConfigurator->findTemplate('Index/index.html'));
    }
```

try it like this

**Comment by Stefan-JustMe69-SQ** [comment]
tried:

```
Compile Error: Declaration of FrontendBundle\CoreShop\Controller\IndexController::indexAction(Symfony\Component\HttpFoundation\Request $request, CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface $templateConfigurator): Symfony\Component\HttpFoundation\Response 
must be compatible with CoreShop\Bundle\FrontendBundle\Controller\IndexController::indexAction(Symfony\Component\HttpFoundation\Request $request): Symfony\Component\HttpFoundation\Response
```

**Comment by dpfaffenbauer** [comment]
ah sorry, extend from FrontendController and not BaseIndexController

**Comment by Stefan-JustMe69-SQ** [comment]
```php
use CoreShop\Bundle\FrontendBundle\Controller\FrontendController;
use CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class IndexController extends FrontendController
{
    public function __construct(protected TemplateConfiguratorInterface $templateConfigurator, protected $container)
    {
        parent::__construct($this->container);
    }


    public function indexAction(Request $request, TemplateConfiguratorInterface $templateConfigurator): Response
    {
//        return $this->render($this->getTemplateConfigurator()->findTemplate('Index/index.html'));
        return $this->render($this->getTemplateConfigurator()->findTemplate('Index/index.html'), ['is_home' => true]);

//        return $this->render('Index/index.html.twig', ['is_home' => true]);
    }
}
```

```
    FrontendBundle\CoreShop\Controller\IndexController:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - 'controller.service_arguments'
            - 'container.service_subscriber'
        arguments:
            - '@CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface'
            - '@service_container'

```

Still error:
![grafik](https://github.com/coreshop/CoreShop/assets/23456403/92703dcb-0847-45b9-a765-31e4a242c53d)

**Reply by dpfaffenbauer** [reply]
```php
use CoreShop\Bundle\FrontendBundle\Controller\FrontendController;
use CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class IndexController extends FrontendController
{
    public function indexAction(Request $request, TemplateConfiguratorInterface $templateConfigurator): Response
    {
        return $this->render($templateConfigurator->findTemplate('Index/index.html'), ['is_home' => true]);
    }
}
```
```yaml
    FrontendBundle\CoreShop\Controller\IndexController:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - 'controller.service_arguments'
            - 'container.service_subscriber'
```

**Comment by Stefan-JustMe69-SQ** [comment]
Sorry,
still the same error
```
The "CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

**Comment by Stefan-JustMe69-SQ** [comment]
I have the solution

Docs saying for own class 'TemplateConfigurator' configuration is needed as followed:
```
# config/services.yaml
services:
  App\CoreShop\TemplateConfigurator\TemplateConfigurator:
    decorates: 'CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfigurator'
```

I have to use:
```
services:
    CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface:
        class: FrontendBundle\CoreShop\TemplateConfigurator\TemplateConfigurator
        public: true

    FrontendBundle\CoreShop\TemplateConfigurator\TemplateConfigurator:
        decorates: 'CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfigurator'
        public: true
```

Without the first 3 lines of configuration above, error is always shown:
```
The "CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface" service or alias 
has been removed or inlined when the container was compiled. You should either make it public, 
or stop using the container directly and use dependency injection instead.
```

Now frontend is showing up, with own IndexController:
```php
<?php

declare(strict_types=1);

namespace FrontendBundle\CoreShop\Controller;

use CoreShop\Bundle\FrontendBundle\Controller\FrontendController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class IndexController extends FrontendController
{

    public function indexAction(Request $request): Response
    {
        return $this->render($this->getTemplateConfigurator()->findTemplate('Index/index.html'));
    }

}
```

and config:
```
core_shop_frontend:
    controllers:
        index: FrontendBundle\CoreShop\Controller\IndexController
```

and config:
```
    FrontendBundle\CoreShop\Controller\IndexController:
        public: true
        tags:
            - 'controller.service_arguments'
            - 'container.service_subscriber'
        arguments:
          [ '@Psr\Container\ContainerInterface' ]
```

I suggest to change documentation.
