### DISCUSSION TITLE
Overriding the StorageListController causes an error

### DISCUSSION THREAD

**Discussion by twin-elements** [coreshop/CoreShop#2764] [Q&A] [answered]
I want to create a wishlist and the current functionality of the StorageListController does not fit me.

Currently WishlistController is a copy of StorageListController

In the file `/config/packages/core_shop_storage_list.yaml`, I only overwrote the controller and templates 

```
core_shop_storage_list:
    list:
        wishlist:
            templates:
                add_to_cart: 'coreshop/Product/_addToWishlist.html.twig'
                summary: 'coreshop/Wishlist/summary.html.twig'
            controller:
                enabled: true
                class: App\Controller\CoreShop\WishlistController
```

I'm checking to see if these changes work. In the `CoreShop\Bundle\StorageListBundle\DependencyInjection\CoreShopStorageListExtension` file, I checked that the arguments are correct. And they were changed correctly.
![image](https://github.com/user-attachments/assets/e8a2e993-2f5a-4e08-bd14-50e25a281566)

But all the time I get the error 
`Cannot autowire service "App\Controller\CoreShop\WishlistController": argument "$identifier" of method "__construct()" is type-hinted "string", you should configure its value explicitly.`

![image](https://github.com/user-attachments/assets/85c247e3-247b-4720-8815-eec672786756)

P.S. I thought that perhaps Symfony when defining services for controllers overrides this and I trotted out this controller. But that didn't do anything either.
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Controller\:
        resource: ../src/Controller
        public: true
        tags:
            - controller.service_arguments
        exclude:
            - '../Controller/CoreShop/WishlistController'
```

**Comment by twin-elements** [comment, marked as answer]
However, it was necessary to exclude the controller from the registration of services
```
    App\Controller\:
        resource: ../src/Controller
        public: true
        tags:
            - controller.service_arguments
        exclude:
            - '../src/Controller/CoreShop/WishlistController.php'
```

Now the new controller works as it should
