### ISSUE TITLE
Add custom condition for pricing rule

### ISSUE THREAD

**Issue by gicuturetchi** [coreshop/CoreShop#1007]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no

I tried to add a new condition for price rules. The idea is I created a model ProductSupplier and I want to put a price depending customer and supplier. Now I tried to add this custom condition but doesn't appear in admin select box. I tried like this : 
CustomCondition.php
```php
namespace AppBundle\CoreShop;

use CoreShop\Component\Resource\Model\ResourceInterface;
use CoreShop\Component\Rule\Model\RuleInterface;

final class CustomCondition implements \CoreShop\Component\Rule\Condition\ConditionCheckerInterface
{
    public function isValid(ResourceInterface $subject, RuleInterface $rule, array $configuration, $params = [])
    {
        return true;
    }
}
```
custom_condition.js
//AppBundle/Resources/public/pimcore/js/custom_condition.js
```js
pimcore.registerNS('coreshop.product.specificprice.conditions.custom');
coreshop.product.specificprice.conditions.timespan = Class.create(coreshop.product.pricerule.conditions.custom, {});
```

//AppBundle/Resources/config/services.yml
```yml
app.product_price_rule.custom_condition:
        class: AppBundle\CoreShop\CustomCondition
        tags:
            - { name: coreshop.product_price_rule.condition, type: custom, form-type: AppBundle\Form\Type\ConditionType }
```
```yml
//app/config/config.yml
core_shop_product:
    pimcore_admin:
        js:
            supplier_condition: '/bundles/app/pimcore/js/custom_condition.js'
```
