### ISSUE TITLE
Frontend Controller Autowiring

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1139]
| Q                | A
| ---------------- | -----
| Bug report?      | sort of
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

How to use autowired, project based controller?

***

For example, i want to use my custom category controller:

```yml
core_shop_frontend:
    controllers:
        category: AppBundle\Controller\CategoryController
```

There are two ways to register my controller:

my controllers as resources, defined in AppBundle:

```yml

# Appbundle/Resources/config/services.yml

    AppBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ['@service_container']]
```

my controller as single service:

```yml

# app/config/services/controller.yml

    AppBundle\Controller\CategoryController:
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ['@service_container']] # not required because of coreshops abstract?
            - [setRouter, ['@router']]

None of them are working in combination with custom coreshop controllers.
