### ISSUE TITLE
Harmonize Form/Entity Validation 

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1152]
| Q                | A
| ---------------- | -----
| Bug report?      | sort of
| Feature request? | sort of
| BC Break report? | no
| RFC?             | yes

There are a lot of validation / constraint stuff in coreshop and sometimes there are some annoying mismatches. 

For example, I want to improve the customers `password` field constraints in the whole ecosystem. I'm starting with the customer entity:

```yaml
CoreShop\Component\Customer\Model\Customer:
    getters:
        password:
            - Length: { min: 8, minMessage: 'foo.bar.customer.password.min' }
```

Done. From now on, my registration form validates the password field against 8 characters.
But now I also need to add a form extension to `ChangePasswordType` and `ResetPasswordType` because they don't validate new data on entity level. This is pure pain.

***

Only if a form contains a corresponding data class, the validation gets dispatched automatically. So adding a validation before saving a customer could solve this:

```php
$this->get('validator')->validate($customer)
```

## Mission
Find a consistent way for all forms and entities, so we can easily modify or extend validations:

- Custom coreshop form / entity validation configuration for example
- Add validation(Via Validator) in every action if no form data class is available for example
