### ISSUE TITLE
[Tracker] Cannot use coreshop.tracking.tracker

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1619]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Tracker does net get recognized by `CoreShopTrackingExtension`:

```yaml
services:
    AppBundle\CoreShop\Tracking\Tracker\MyTracker:
        parent: CoreShop\Bundle\TrackingBundle\Tracker\AbstractEcommerceTracker
        calls:
            - [ setCodeTracker, [ '@CoreShop\Bundle\TrackingBundle\Tracker\Google\TagManager\CodeTracker' ] ]
            - [ setConfigResolver, [ '@CoreShop\Bundle\TrackingBundle\Resolver\ConfigResolver' ] ]
        tags:
            - { name: coreshop.tracking.tracker, type: my-tracker }
```

Also: `registerForAutoconfiguration` should only be used, if no further attributes are required. Tracker classes need to deliver a `type` attribute, so autoconfiguration is not possible!
