### ISSUE TITLE
Homepage :: Login :: 500 error

### ISSUE THREAD

**Issue by ivicafactory** [coreshop/CoreShop#1763]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | no
| RFC?             | no

When trying to log in from homepage I get an error no matter what I type in into login fields.
Screen recording: https://watch.screencastify.com/v/ytubuFKqUJiaZ6fdXVi5
Stack trace:
```
RuntimeException:
You must configure the check path to be handled by the firewall.

  at vendor/coreshop/core-shop/src/CoreShop/Bundle/FrontendBundle/Controller/SecurityController.php:67
  at CoreShop\Bundle\FrontendBundle\Controller\SecurityController->checkAction()
     (vendor/symfony/http-kernel/HttpKernel.php:156)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:78)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:199)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:36)     
```

**Comment by dpfaffenbauer** [comment]
did you install the security.yml?

**Comment by mekicleon** [comment]
Hey Dominik. Can you please give us a hint on how this should be solved.
Currently i have setup security yml like I did on every other pimcore project
security.yml:
  ```
      coreshop:
            anonymous: true
            provider: customer_provider
            form_login:
                login_path: ‘/en/shop/login’
                check_path: ‘/en/shop/login’
                success_handler: AppBundle\EventListener\AuthenticationLoginListener
                failure_handler: AppBundle\EventListener\AuthenticationLoginListener
            logout:
                path: ‘logout’
                invalidate_session: false
                success_handler: AppBundle\EventListener\AuthenticationLogoutListener
```
services.yml:
```
     app.customer.provider:
        class: App\Security\UserProvider\CustomerProvider
        public: true
    AppBundle\EventListener\AuthenticationLoginListener:
        class: App\EventListener\AuthenticationLoginListener
        public: true
    AppBundle\EventListener\AuthenticationLogoutListener:
        class: App\EventListener\AuthenticationLogoutListener
        public: true
    PasswordFieldEncoder:
        class: Pimcore\Security\Encoder\Factory\UserAwareEncoderFactory
        arguments:
            - Pimcore\Security\Encoder\PasswordFieldEncoder
            - [ ‘password’ ]
```
I have successfully setup these changes and now login works but I’m questioning if this is the right path to go with because these changes required an override of CoreShop customer class. The override was necessary because of CustomerManagementFrameworkBundle\Model\CustomerInterface (I returned the values for street, zip, …. from CoreShopAddress object that is in relation with CustomerObject). But now I realised this is probably wrong because im using CMF classes.
Can you please point me in the right direction.

**Comment by dpfaffenbauer** [comment]
you can combine cmf and CoreShop. Difference is that CoreShop uses a very simple class for the login (User) and a more complex class for the actual Person behind the Login (Customer). The Customer you use for CoreShop just needs to implement the CustomerInterface of CoreShop, that can be basically any DataObject Class. You can change the CoreShop Customer like this:

```yml
core_shop_customer:
    pimcore:
        customer:
            classes:
                model: 'Pimcore\Model\DataObject\YourCustomerClass'
```
