### ISSUE TITLE
disabled payment step - no order possible

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1827]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

when disabling payment via configuration (https://docs.coreshop.org/2.1.0/Development/Checkout/Checkout_Manager.html), ordering is not possible:
```
CoreShop\Component\Payment\Model\Payment::setPaymentProvider(): Argument #1 ($paymentProvider) 
must be of type CoreShop\Component\Payment\Model\PaymentProviderInterface, null given, 
called in /var/www/dev/vendor/coreshop/core-shop/src/CoreShop/Component/Order/Payment/OrderPaymentProvider.php on line 47
```
CoreShop 3 beta 2

config/config.yml:
```
core_shop_core:
    checkout:
        default:
            steps:
                shipping: false
                payment: false         
```
