### ISSUE TITLE
Static routes created empty, with UUIDs as names

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#1886]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Running `coreshop:install` on a brand new Pimcore 10.3 project, I get a lot of static routes generated which look like this

```yaml
pimcore:
    staticroutes:
        definitions:
            cf9f8210-6374-4a32-b58b-b235f43c7a4e:
                name: null
                pattern: null
                reverse: null
                controller: null
                variables: null
                defaults: null
                siteId: null
                methods: null
                priority: 1
                creationDate: 1646666235
                modificationDate: 1646666235
```
