### ISSUE TITLE
\CoreShop\Component\SEO\Extractor\ImageExtractor hardcodes Tool::getHostUrl() as prefix

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2010]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The thumbnail URL can be pointing to an external storage (via CDN) which is [configured](https://pimcore.com/docs/pimcore/10.0/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/File_Storage_Setup.html) via
```yaml
pimcore:
   assets:
       frontend_prefixes:
           thumbnail: https://tavi-12345678990.cloudfront.net/thumbnail
```
