### ISSUE TITLE
User Session gone after Offsite Payment

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2168]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If you're using an offsite payment, the user session is gone, after the user returns to the thank you / revise page.

Changing the cookie_samesite property to `lax` solves the issue:

```yaml
framework:
    session:
        cookie_samesite: 'lax'
```

If there is no other way to fix this, this should be added to the installation docs.
