### ISSUE TITLE
How to overwrite order number generation

### ISSUE THREAD

**Issue by lukadschaak** [coreshop/CoreShop#2312]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Type | Just a question |

Hi!

Background: i want to change the order number that is generated when summiting an order via checkout.

The only solution it found was to create a new symfony service and decorate the default number generator. An example is below.

My question is: Is there a better way of doing this? in this configuration you have to work with `decoration_priority` to either be called before the `prefix_suffix` generator, or after it.

If you choose `decoration_priority` to be `>= 0`, the order of called decoraters would be  `PrefixSuffix Generator > PaddingNumberGenerator > DefaultSequenceGenerator`
If you choose a `decoration_priority: -1`, the order of called decoraters would change to `PaddingNumberGenerator > PrefixSuffix Generator > DefaultSequenceGenerator`

Additional question: If this implementation seems okay for you guys, do you think it is worth to document it?

```yaml
  App\Order\PaddingNumberGenerator:
    decorates: coreshop.order.number_generator.default
    decoration_priority: 1
    arguments:
      - '@.inner'
      - 8 # order number padding length
```

```php
final class PaddingNumberGenerator implements NumberGeneratorInterface
{
    public function __construct(
        private NumberGeneratorInterface $numberGenerator,
        private int $paddingLength,
    ) {
    }

    public function generate(ResourceInterface $model): string
    {
        $number = $this->numberGenerator->generate($model);

        return str_pad($number, $this->paddingLength, '0', STR_PAD_LEFT);
    }
}
