### ISSUE TITLE
missing service security.event_dispatcher.coreshop_frontend

### ISSUE THREAD

**Issue by sevarozh** [coreshop/CoreShop#2401]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

pimcore 11.0.12
core-shop 4.0.x-dev

PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "security.event_dispatcher.coreshop_frontend"

service is in vendor/coreshop/core-shop/src/CoreShop/Bundle/CoreBundle/Resources/config/services/handler.yml defined but class CoreShop\Bundle\CoreBundle\EventListener\ShopUserLogoutHandler is not exists

**Comment by dpfaffenbauer** [comment]
Did you add the firewall configuration for CoreShop in `config/packages/security.yaml`?

```
        coreshop_frontend:
            provider: coreshop_user
            pattern: '%coreshop.security.frontend_regex%'
            context: shop
            form_login:
                login_path: coreshop_login
                check_path: coreshop_login_check
                provider: coreshop_user
                failure_path: coreshop_login
                default_target_path: coreshop_index
                use_forward: false
                use_referer: true
            remember_me:
                secret: "%secret%"
                name: APP_CORESHOP_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: coreshop_logout
                target: coreshop_login
                invalidate_session: false

```

**Comment by sevarozh** [comment]
ja, aber das hilft leider nicht

**Comment by dpfaffenbauer** [comment]
I just installed Pimcore 11.0.12 added this to the security config and it worked:

```
parameters:
    coreshop.security.frontend_regex: "^/(?!admin)[^/]*"

security:
    enable_authenticator_manager: true

    providers:
        ....
        coreshop_user:
            id: CoreShop\Bundle\CoreBundle\Security\ObjectUserProvider

    firewalls:
       ....
        coreshop_frontend:
            provider: coreshop_user
            pattern: '%coreshop.security.frontend_regex%'
            context: shop
            form_login:
                login_path: coreshop_login
                check_path: coreshop_login_check
                provider: coreshop_user
                failure_path: coreshop_login
                default_target_path: coreshop_index
                use_forward: false
                use_referer: true
            remember_me:
                secret: "%secret%"
                name: APP_CORESHOP_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: coreshop_logout
                target: coreshop_login
                invalidate_session: false
```
