### ISSUE TITLE
[Pimcore 11 / Bug] Admin UI light theme does not contrast with icons

### ISSUE THREAD

**Issue by NiklasBr** [coreshop/CoreShop#2566]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

It looks like this:
![image](https://github.com/coreshop/CoreShop/assets/279826/3ff25885-aa84-45ac-8c57-fbedb179cd2d)
And on hover it is good:
![image](https://github.com/coreshop/CoreShop/assets/279826/900c518a-c4c4-4ab3-a483-f42825fcd9de)

This is the full CSS path selector to the `li` menu item, unfortunately I cannot find anything which signals the light theme is used:

```css
html#ext-element-6.x-viewport 
body#ext-element-1.pimcore_version_11.x-gecko.x-windows.x-desktop.x-body.x-keyboard-mode.x-border-box.x-scroller.x-container.x-container-default 
div#pimcore_sidebar.with-notifications 
div#pimcore_navigation 
ul#pimcore_navigation_ul 
li#pimcore_menu_coreshop_coreshop.pimcore_menu_item.pimcore_menu_needs_children.coreshop_logo_menu.true-initialized
```

Pimcore themselves resolved it by inverting the icons in `pimcoreadminuiclassiclighttheme/css/admin.css`:

```css
#pimcore_navigation .x-menu-item-icon, .pimcore_navigation_flyout .x-menu-item-icon-default, .pimcore_panel_toolbar_horizontal .pimcore_main_toolbar .x-btn-icon-el, .pimcore_panel_toolbar_horizontal_border_layout .pimcore_main_toolbar .x-btn-icon-el, .pimcore_editor_tabbar .x-tab-icon-el, .pimcore_main_accordion .pimcore_icon_material, .pimcore_headbar_submenu_menu .x-menu-item-icon, .x-menu .pimcore_nav_icon_custom_report_default, #pimcore_panel_tabs > .x-panel-bodyWrap > .x-tab-bar .x-tab-bar-body .backend_power_tools_admin_bookmark_list {
    filter: invert(0.7);
}
```
