### ISSUE TITLE
Cannot install CoreShop ^4.0 with Pimcore ^11.1

### ISSUE THREAD

**Issue by gander** [coreshop/CoreShop#2582]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

1. Install **Pimcore** `^11.1` [Docker Based Installation](https://pimcore.com/docs/platform/Pimcore/Getting_Started/Installation/Docker_Based_Installation)
2. Fullfill **CoreShop** `php-xsl` requirement:
```yaml
services:
    php:
        build:
            dockerfile_inline: |
                FROM pimcore/pimcore:php8.2-debug-latest
                RUN apt-get update && apt-get install --yes gcc autoconf pkg-config make libxslt-dev
                RUN docker-php-ext-install xsl
```
3. Try install **CoreShop** `^4.0`:
```shell
docker compose exec php composer require coreshop/core-shop ^4.0
```
Error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - coreshop/core-shop[4.0.0, ..., 4.0.4] require sebastian/diff ^4.0 | ^5.0 -> found sebastian/diff[4.0.0, ..., 4.0.6, 5.0.0, ..., 5.1.1] but the package is fixed to 6.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires coreshop/core-shop ^4.0 -> satisfiable by coreshop/core-shop[4.0.0, ..., 4.0.4].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Downgrading Pimcore dependency packages is not a solution. Moreover, these conflicts cannot be resolved with `--with-all-dependencies`
