### ISSUE TITLE
CoreShop 4 - Extending Frontend Controllers

### ISSUE THREAD

**Issue by Stefan-JustMe69-SQ** [coreshop/CoreShop#2635]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I followed documentation
https://docs.coreshop.org/CoreShop/Development/Frontend_Bundle/
an created own class TemplateConfigurator

```php
<?php

declare(strict_types=1);

namespace FrontendBundle\CoreShop\TemplateConfigurator;

use CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface;

class TemplateConfigurator implements TemplateConfiguratorInterface
{
    public function findTemplate(string $templateName): string
    {
        return sprintf('coreshop/%s.twig', $templateName);
    }
}


    FrontendBundle\CoreShop\TemplateConfigurator\TemplateConfigurator:
        decorates: 'CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfigurator'
        public: true


```

I created controller IndexController and followed description in
https://docs.coreshop.org/CoreShop/Development/Frontend_Bundle/Controllers
and created controller and configuration as described

my class:
```php
<?php

declare(strict_types=1);

namespace FrontendBundle\CoreShop\Controller;

use CoreShop\Bundle\FrontendBundle\Controller\FrontendController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class IndexController extends FrontendController
{

    public function indexAction(Request $request): Response
    {
        return $this->render($this->getTemplateConfigurator()->findTemplate('Index/index.html'));
    }
}
```

my configs:
```
    FrontendBundle\CoreShop\Controller\IndexController:
        public: true
        arguments:
            - '@service_container'

core_shop_frontend:
    controllers:
        index: FrontendBundle\CoreShop\Controller\IndexController
```

I'm getting error:
```
The "CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

How to fix that?
