### ISSUE TITLE
Menu Icon for Pimcore Enterprise Light Theme

### ISSUE THREAD

**Issue by breakone** [coreshop/CoreShop#2776]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

The menu icon is white and so not visible in the Enterprise Light Theme. Check, if admin-ui-classic-light-theme-bundle is installed and add e.g. css class for light theme.

<img width="104" alt="image" src="https://github.com/user-attachments/assets/d3f1d88a-d8fa-473f-891a-6f2e1ee2d816" />

**Comment by NiklasBr** [comment]
A partial solution was to fill the SVG with the text colour with an CSS rule like this, it would work in both themes, maybe it can help?

```css
#pimcore_sidebar #pimcore_navigation li svg path {
    fill: currentcolor;
}
```
