### ISSUE TITLE
[Bug]: Error after updating to 4.1.0, when trying to finish order

### ISSUE THREAD

**Issue by Stefan-JustMe69-SQ** [coreshop/CoreShop#2797]
Using pimcore 11.5.3 and coreshop 4.1.0

After updating from 4.0.11 to 4.1.0 and activating CoreShopFrontendBundle, when I try to complete order (quote) action, before thank-you page I get:

```
Symfony Exception
[ Symfony Docs](https://symfony.com/doc/6.4.18/index.html)
[RuntimeException](https://dev11.klio.com/de/shop/cart/quote#trace-box-1)
HTTP 500 Internal Server Error
Could not resolve argument $machineManager of "CoreShop\Bundle\FrontendBundle\Controller\CartController::createquoteaction()", maybe you forgot to register the controller as a service or missed tagging it with the "controller.service_arguments"?

Symfony\Component\DependencyInjection\Exception\
RuntimeException
in vendor/symfony/http-kernel/Controller/ArgumentResolver/NotTaggedControllerValueResolver.php (line 88)
in [vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php ](file:///var/www/dev2/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php#L60)-> resolve (line 60)
in [vendor/symfony/http-kernel/Controller/ArgumentResolver.php ](file:///var/www/dev2/vendor/symfony/http-kernel/Controller/ArgumentResolver.php#L91)-> resolve (line 91)
in [vendor/symfony/http-kernel/Controller/TraceableArgumentResolver.php ](file:///var/www/dev2/vendor/symfony/http-kernel/Controller/TraceableArgumentResolver.php#L40)-> getArguments (line 40)
in [vendor/symfony/http-kernel/HttpKernel.php ](file:///var/www/dev2/vendor/symfony/http-kernel/HttpKernel.php#L173)-> getArguments (line 173)
in [vendor/symfony/http-kernel/HttpKernel.php ](file:///var/www/dev2/vendor/symfony/http-kernel/HttpKernel.php#L76)-> handleRaw (line 76)
in [vendor/symfony/http-kernel/Kernel.php ](file:///var/www/dev2/vendor/symfony/http-kernel/Kernel.php#L197)-> handle (line 197)
in [vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php ](file:///var/www/dev2/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php#L35)-> handle (line 35)
in [vendor/autoload_runtime.php ](file:///var/www/dev2/vendor/autoload_runtime.php#L29)-> run (line 29)
require_once('/var/www/dev2/vendor/autoload_runtime.php')
in [public/index.php ](file:///var/www/dev2/public/index.php#L19)(line 19)
```

Is there something I missed for updating?

In BE I can see cart-object.

Additional: We have our own FrontendBundle\Controller\CartController

Config:
```
    FrontendBundle\CoreShop\Controller\CartController:
        public: true
        tags:
            - 'controller.service_arguments'
            - 'container.service_subscriber'
        arguments:
          [ '@Psr\Container\ContainerInterface' ]
```
and
```
core_shop_frontend:
    controllers:
        index: FrontendBundle\CoreShop\Controller\IndexController
        register: FrontendBundle\CoreShop\Controller\RegisterController
        search: FrontendBundle\CoreShop\Controller\SearchController
        cart: FrontendBundle\CoreShop\Controller\CartController
        customer: FrontendBundle\Controller\CustomerController
```

the createQuoteAction function is identical to vendor/coreshop/core-shop/src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php

**Comment by Stefan-JustMe69-SQ** [comment]
Any tips / workaround / help for the problem ?

**Comment by dpfaffenbauer** [comment]
@JustMe69 haven't had time yet to look at it. probably this week.

**Comment by dpfaffenbauer** [comment]
@JustMe69 Can you run the following? `bin/console debug:container CoreShop\\Bundle\\FrontendBundle\\Controller\\CartController`

**Comment by Stefan-JustMe69-SQ** [comment]
```
bin/console debug:container CoreShop\\Bundle\\FrontendBundle\\Controller\\CartController

Information for Service "CoreShop\Bundle\FrontendBundle\Controller\CartController"
==================================================================================

 ---------------- ----------------------------------------------------------
  Option           Value
 ---------------- ----------------------------------------------------------
  Service ID       CoreShop\Bundle\FrontendBundle\Controller\CartController
  Class            FrontendBundle\CoreShop\Controller\CartController
  Tags             controller.service_arguments
                   container.service_subscriber
                   container.service_subscriber
  Public           yes
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        no
  Autoconfigured   no
  Usages           none
 ---------------- ----------------------------------------------------------
```

```
bin/console debug:container FrontendBundle\\CoreShop\\Controller\\CartController

Information for Service "FrontendBundle\CoreShop\Controller\CartController"
===========================================================================

 ---------------- ---------------------------------------------------
  Option           Value
 ---------------- ---------------------------------------------------
  Service ID       FrontendBundle\CoreShop\Controller\CartController
  Class            FrontendBundle\CoreShop\Controller\CartController
  Tags             controller.service_arguments
                   container.service_subscriber
                   container.service_subscriber
  Public           yes
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        no
  Autoconfigured   no
  Usages           none
 ---------------- ---------------------------------------------------
```

**Comment by dpfaffenbauer** [comment]
and for CoreShop\Bundle\FrontendBundle\Controller\CartController?

**Comment by dpfaffenbauer** [comment]
can ypu try removing your config?

```
    FrontendBundle\CoreShop\Controller\CartController:
        public: true
        tags:
            - 'controller.service_arguments'
            - 'container.service_subscriber'
        arguments:
          [ '@Psr\Container\ContainerInterface' ]
```

CoreShop does this automatically.
