### ISSUE TITLE
Implement Priority in Workflow Callbacks

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#357]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? |no
| RFC?             | no

Add a priority (default `0`) tag to workflow configuration:

```yml
core_shop_workflow:
    state_machine:
        coreshop_order_payment:
            callbacks:
                after:
                    generate_something_useful:
                        on: ['pay']
                        do: ['@service', 'doSomething']
                        args: ['object']
                        priority: 100
 ```
