### ISSUE TITLE
Allow different customer class to be used

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#364]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Similar to product classes https://www.coreshop.org/docs/2.0.0/Development/Products/Multiple_Product_DataObjects.html allow other customer classes so Bundles like CMF or Members can be used.

**Comment by dpfaffenbauer** [comment]
already possible:

```
core_shop_customer:
  pimcore:
    customer:
      classes:
        model: 'Pimcore\Model\DataObject\YourCustomer'
```
