### ISSUE TITLE
[TrackingBundle]: Possible wrong template path in GlobalSiteTagEnhancedEcommerce

### ISSUE THREAD

**Issue by khusseini** [coreshop/CoreShop#655]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

While testing out the Google Tag Management features of Pimcore and Coreshop, we ran into an issue that the gtm template for product views was not found resulting in an exception.
We tracked the error down to be possibly this line https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/TrackingBundle/Tracker/Google/GlobalSiteTagEnhancedEcommerce.php#L58

Here the default option is set to point to the `CoreShopTrackingBundle:Tracking/gtm/classic` folder, which does not carry the `product_view.js.twig`

I am not sure if this is the real source of the issue, or if it is an issue at all for other installations.

**Comment by dpfaffenbauer** [comment]
this potentially sounds like the issue. I will look at that sometime this week and fix it. Before the RC.1 release.

**Comment by khusseini** [comment]
Here some more information and a possible workaround. Unfortunately I am not too familiar with the difference between GTag and and GTM and I am crossing my finger right  now, that both ways are fine.

In the config for the tracking bundle I have for the error case only enabled the `google-gtag-enhanced-ecommerce`. By enabling the `google-gtm-enhanced-ecommerce` the issue might be resolved

So to recap:
- throws an exception:
    ```
    core_shop_tracking:
      trackers:
        google-gtag-enhanced-ecommerce:
          enabled: true
    ```
- this works
    ```
    core_shop_tracking:
      trackers:
        google-gtag-enhanced-ecommerce:
          enabled: false
        google-gtm-enhanced-ecommerce:
          enabled: true
```
